version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: challengetwodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: vlt123456
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  springboot-app:
    build: .
    container_name: challengetwoapp
    ports:
      - "8080:8080"
    depends_on:
      - mongo
volumes:
  mongodb_data: